name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC
  workflow_dispatch: {}

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Update submodules to latest
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          if [ -d "userplugins-equicord" ]; then
            cd userplugins-equicord
            git fetch origin equicord:equicord
            git checkout equicord || git checkout -b equicord origin/equicord
            cd ..
          fi
          if [ -d "equicord" ]; then
            cd equicord
            git fetch origin main:main
            git checkout main || git checkout -b main origin/main
            cd ..
          fi

      - name: Commit and push if submodules updated
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: update submodule references to latest [automated]"
            git push
          else
            echo "No submodule updates."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
